In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [26]:

df = pd.read_csv('DAttention.csv',index_col=0)

In [27]:
df.head()

Task1  Task2  Task3  Z
0      8     13     13  0
1     13     11     12  0
2      7     10     18 -1
3      8     14     11  0
4     11     16     17  1

In [28]:
y = df['Z']
X = df[['Task1', 'Task2', 'Task3']]

In [29]:
df.describe()


Task1       Task2       Task3           Z
count  179.000000  179.000000  179.000000  179.000000
mean    10.301676   12.592179   14.558659    0.039106
std      2.857780    2.371683    2.243760    0.554483
min      6.000000    9.000000   11.000000   -1.000000
25%      8.000000   10.000000   13.000000    0.000000
50%     10.000000   13.000000   15.000000    0.000000
75%     13.000000   15.000000   16.000000    0.000000
max     15.000000   16.000000   18.000000    1.000000

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.40, random_state = 42)

In [32]:
from sklearn import svm


In [33]:
clf = svm.SVC()

In [34]:
clf.fit(X_train, y_train)

/home/shekhar/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [35]:
X_train.shape

(107, 3)

In [36]:
y_predict = clf.predict(X_test)

In [37]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [38]:
accuracy_score(y_test, y_predict)

0.8888888888888888

In [39]:
confusion_matrix(y_test,y_predict)

array([[ 3,  5,  0],
       [ 2, 48,  0],
       [ 0,  1, 13]])

In [40]:
from sklearn.ensemble import RandomForestClassifier

In [41]:
clf = RandomForestClassifier(n_jobs=2, random_state=0)
clf.fit(X_train, y_train)

/home/shekhar/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [42]:
y_predict = clf.predict(X_test)

In [43]:
accuracy_score(y_test, y_predict)

0.9027777777777778

In [44]:
confusion_matrix(y_test,y_predict)

array([[ 4,  4,  0],
       [ 1, 49,  0],
       [ 0,  2, 12]])

In [45]:
from sklearn.naive_bayes import GaussianNB

In [50]:
clf = GaussianNB()
clf.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [51]:
y_predict = clf.predict(X_test)

In [52]:
accuracy_score(y_test, y_predict)

0.8055555555555556

In [53]:
confusion_matrix(y_test,y_predict)

array([[ 2,  6,  0],
       [ 0, 49,  1],
       [ 0,  7,  7]])